import { CharClass } from "../models/CharClass";

export const defaultChars = [
  new CharClass('Pikachu', 'red', 'https://www.playgwent.com/uploads/media/assets_preview/0001/26/thumb_25570_assets_preview_big.jpg', 'Pikachu is an Electric-type Pokémon. It evolves from Pichu when leveled up with high friendship and evolves into Raichu when exposed to a Thunder Stone.'),
  new CharClass('Charmander', 'red', 'https://www.playgwent.com/uploads/media/assets_preview/0001/26/thumb_25447_assets_preview_big.jpg', 'Charmander is a Fire-type Pokémon. It evolves into Charmeleon starting at level 16, which evolves into Charizard starting at level 36.'),
  new CharClass('Bulbasaur', 'green', 'https://www.playgwent.com/uploads/media/assets_preview/0001/32/thumb_31252_assets_preview_big.jpg', 'Bulbasaur is a Grass/Poison-type Pokémon. It evolves into Ivysaur starting at level 16, which evolves into Venusaur starting at level 32.'),
  new CharClass('Squirtle', 'green', 'https://www.playgwent.com/uploads/media/assets_preview/0001/33/thumb_32497_assets_preview_big_e4e3aa4c01666b41725c7a50e94a994281b18a58.jpg', 'Squirtle is a Water-type Pokémon. It evolves into Wartortle starting at level 16, which evolves into Blastoise starting at level 36.'),
  new CharClass('Eevee', 'blue', 'https://www.playgwent.com/uploads/media/assets_preview/0001/27/thumb_26197_assets_preview_big.jpg', 'Eevee is a Normal-type Pokémon. It evolves into one of eight different Pokémon through various methods: Vaporeon when exposed to a Water Stone, Jolteon when exposed to a Thunder Stone, Flareon when exposed to a Fire Stone, Espeon when leveled up with high friendship during the day, Umbreon when leveled up with high friendship during the night, Leafeon when leveled up near a Moss Rock, Glaceon when leveled up near an Ice Rock, and Sylveon when leveled up with high friendship and knowing a Fairy-type move.'),
  new CharClass('Mewtwo', 'blue', 'https://www.playgwent.com/uploads/media/assets_preview/0001/27/thumb_26428_assets_preview_big.jpg', 'Mewtwo is a Psychic-type Pokémon. It is known to be a clone of Mew. It is also known as the Genetic Pokémon.'),
]