import { CharClass } from "../models/CharClass";

import cedric from './factions/cedric.webp';
import seraphina from './factions/seraphina.webp';
import kaelan from './factions/kaelan.webp';
import ingmar from './factions/ingmar.webp';
import dante from './factions/dante.webp';
import tyrell from './factions/tyrell.webp';

export const defaultChars = [
  new CharClass('Prince Cedric', 'red', cedric, 'Prince Cedric Aumont, the eldest son of King Aldric the Wise, founded the Infernal Legion in response to the kingdom\'s descent into chaos following the theft of the Crown Jewel. Fuelled by his ambition to restore order and reclaim his birthright, Cedric leads the Legion with unwavering determination and a fierce sense of duty. Despite his noble upbringing, Cedric is not afraid to get his hands dirty on the battlefield, earning him the respect and loyalty of his followers.'),
  new CharClass('Seraphina Flamebringer', 'red', seraphina, 'Seraphina Flamebringer, a powerful sorceress and former advisor to King Aldric, stands as Prince Cedric\'s trusted lieutenant within the Infernal Legion. Banished from the royal court due to her involvement in forbidden magics, Seraphina found a new purpose in Cedric\'s cause. With her mastery of infernal magic and cunning intellect, she conjures flames of chaos to further their goals, ensuring that the Infernal Legion remains a formidable force to be reckoned with in the struggle for control of Estoria.'),
  new CharClass('Kaelan Thorn', 'green', kaelan, 'Captain Kaelan Thorn is a seasoned mercenary warrior hailing from distant lands. With a reputation for his strategic brilliance and unwavering loyalty to his comrades, Kaelan leads the Oakheart Hanse with honour and determination. Drawn into the conflict to recover the stolen Crown Jewel, he sees the mission as an opportunity to secure wealth and prosperous future for his band of mercenaries while remaining true to his principles.'),
  new CharClass('Ingmar Stormborn', 'green', ingmar, 'Ingmar Stormborn, a seasoned warrior from the north, joined the Oakheart Hanse in their quest to recover the stolen Crown Jewel. With his fierce demeanour and unwavering loyalty, Ingmar quickly rose to a position of leadership within the group. Ingmar sees the mission as an opportunity to prove himself in battle and secure glory and fame for himself and his comrades within the Oakheart Hanse.'),  
  new CharClass('Dante Nightshade', 'blue', dante, 'Dante Nightshade is a shadowy figure shrouded in mystery, rumoured to have once been a trusted agent of the crown before his fall from grace. Exiled for crimes he claims he did not commit, Dante now leads the Shadow Brotherhood with cunning and ruthlessness. Determined to uncover the truth behind his betrayal, he manoeuvres through the shadows of Estoria, seeking to reclaim his lost honour and secure the Crown Jewel for his own enigmatic purposes.'),
  new CharClass('Tyrell Darkheart', 'blue', tyrell, 'Tyrell Darkheart is a seasoned warrior and skilled operative of the Shadow Brotherhood. With a background in covert operations and hand-to-hand combat, Tyrell is Dante\'s right-hand man in the field. Fearless and determined, he carries out missions with precision and efficiency, striking fear into the hearts of their enemies. With his unwavering loyalty to the Brotherhood and his expertise in combat, Tyrell plays a crucial role in their quest to reclaim the Crown Jewel and reshape the fate of Estoria.'),
]